set(7z_ROOT "${SDK_PATH}/7z/x64")
string(REPLACE "\\" "/" 7z_ROOT ${7z_ROOT})
if (NOT EXISTS ${7z_ROOT}/bin/7za.dll)
	message(FATAL_ERROR "7za.dll not found")
endif()
file(COPY ${7z_ROOT}/bin/7za.dll DESTINATION ${CMAKE_BINARY_DIR}/bin/${CMAKE_BUILD_TYPE})
