set(7z_ROOT "${SDK_PATH}/7z/x64")
string(REPLACE "\\" "/" 7z_ROOT ${7z_ROOT})
if (NOT EXISTS ${7z_ROOT}/bin/7z.dll)
	message(FATAL_ERROR "7z.dll not found")
endif()
file(COPY ${7z_ROOT}/bin/7z.dll DESTINATION ${CMAKE_BINARY_DIR}/bin)
install(FILES ${7z_ROOT}/bin/7z.dll DESTINATION .)
